### ISSUE TITLE
installing unibeautify to an existing docker image

### ISSUE THREAD

**Issue by daybreak10** [Unibeautify/docker-beautifiers#31]
I see how to pull an already configured image, but I have a docker image already created with my application stack requirements.  How do I add unibeautify to my existing container?  Thanks.

**Comment by Glavin001** [comment]
You may need to copy parts of the `Dockerfile` by hand or use something like Docker multi-stage builds with `COPY --from`: https://docs.docker.com/develop/develop-images/multistage-build/

Any more information you could provide? Like your current `Dockerfile`, for example?

**Comment by daybreak10** [comment]
Initial dockerfile is below, but we (the developer that owns the docker file and I) had problems with systemctl and the OCI8, which part had to be installed after we got the initial image up and running.  I have also installed the following after this initial image was built....

- xdebug
- mariadb
- php-pdo and php-pdo_mysql
- composer

I am using ATOM and have both atom-beautifier and php-cs-fixer packages installed, but they are giving me errors so I thought this might be what I have to fix first.  Thanks!

Initial dockerfile:  
```dockerfile
FROM centos/systemd

MAINTAINER {information redacted}

RUN yum -y install httpd; yum -y install rpm-build rpmdevtools
RUN yum -y install libaio; yum -y install gcc; yum -y install make
RUN yum -y install php php-common php-devel php-pear
ADD oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm /oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm
RUN rpm -Uvh /oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm
ADD oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm /oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm
RUN rpm -Uvh oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm
ADD oracle-instantclient11.2-sqlplus-11.2.0.4.0-1.x86_64.rpm /oracle-instantclient11.2-sqlplus-11.2.0.4.0-1.x86_64.rpm
RUN rpm -Uvh oracle-instantclient11.2-sqlplus-11.2.0.4.0-1.x86_64.rpm
ADD oci8-2.0.12 /oci8-2.0.12
RUN cd oci8-2.0.12; phpize; ./configure --with-oci8=instantclient,/usr/lib/oracle/11.2/client64/lib; make install
RUN echo "extension=oci8.so" > /etc/php.d/oci8.ini
RUN mkdir -p /var/www/html
RUN cd /; rm oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm; rm oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm; rm oracle-instantclient11.2-sqlplus-11.2.0.4.0-1.x86_64.rpm; rm -r oci8-2.0.12
ADD nodejs-7.10.0-1nodesource.el7.centos.x86_64.rpm /nodejs-7.10.0-1nodesource.el7.centos.x86_64.rpm
RUN rpm -Uvh /nodejs-7.10.0-1nodesource.el7.centos.x86_64.rpm
RUN rpmdev-setuptree
RUN echo "date.timezone = UTC" >> /etc/php.ini
RUN yum clean all; systemctl enable httpd.service

EXPOSE 80

CMD ["/usr/sbin/init"] 
```

**Comment by Glavin001** [comment]
@daybreak10 Which of Unibeautify's beautifier Docker images are you interested in adding? https://github.com/Unibeautify/docker-beautifiers#docker-images

I wonder why you would want to add these into your existing image. Atom-Beautify uses these beautifier Docker images directly.

---

> I am using ATOM and have both atom-beautifier and php-cs-fixer packages installed, but they are giving me errors so I thought this might be what I have to fix first. Thanks!

I think you should create a question issue over at [Atom-Beautify](https://github.com/Glavin001/atom-beautify/) and include a `debug.md` Gist.

This does not sound like an appropriate issue for this repository 😜 .
