### ISSUE TITLE
docker image does not launch to linux command prompt

### ISSUE THREAD

**Issue by daybreak10** [Unibeautify/docker-beautifiers#32]
Follow up from [Unibeautify/docker-beautifiers] installing unibeautify to an existing docker image (#31) where Glavin Wiechert recommended using the existing image.  I pulled it as indicated on this code page, and then attempted to launch it.  I receive only the result of the version command when I do this....

```
docker run -it -v C:/ATOMDevelopment:/var/www/html unibeautify/php-cs-fixer:latest "--version"
PHP CS Fixer 2.13.1 Yogi's BBQ by Fabien Potencier and Dariusz Ruminski (54814c6)
```

And if I try to add the /bin/bash at the end of the line, it just returns to the DOS prompt and does not launch the linux container instance, or at least not that I can get to a command line.   But if I look at the container created in Kitematic, the container logs say "command /bin/bash is not defined". 

Not sure how to get command line access to this container so that I can see what tools are installed, etc.  Can you advise?  Thanks.

**Comment by stevenzeck** [comment]
@daybreak10 What are you trying to do exactly?  I can try helping with the command once I know that.

**Comment by daybreak10** [comment]
Goal: get to a linux command prompt inside of the docker container launched from this downloaded image.  I can then navigate in the linux environment using standard commands cat, vi, service (or systemctl), etc.  If I was to use this as my base container and then make changes that need to be committed to my own variation of this container, I need to have linux command line access.  Hope that answers the question.

**Comment by stevenzeck** [comment]
It sounds like you need to create your own Dockerfile and use this one as a starting point, similar to how we use [Alpine PHP](https://github.com/Unibeautify/docker-beautifiers/blob/master/php-cs-fixer/Dockerfile#L1).

But if you just want to start the image and not run the default php-cs-fixer command, you'll need to override the entrypoint.  So something like this:  `docker run -it --entrypoint="" unibeautify/php-cs-fixer "/bin/sh"`

**Comment by daybreak10** [comment]
Thanks, I have my own image and my initial query was how to add this to that image so that I can use unibeautify in ATOM.  That's when the recommendation was made to use the existing image called unibeautify/php-cs-fixer.  It appears I'm just not going to be able to do what I want to do, so please close this issue as unresolved.

**Comment by stevenzeck** [comment]
Unibeautify will be available in Atom.  I'm going to write up instructions to install the Unibeautify branch of Atom-Beautify in Atom.
