### ISSUE TITLE
Uncrustify image needs updating

### ISSUE THREAD

**Issue by stevenzeck** [Unibeautify/docker-beautifiers#9]
The base image used for unibeautify/uncrustify, sonatest/docker-uncrustify, no longer exists.  Although it doesn't affect current pulls, keeping up to date with the latest version of uncrustify won't be possible.

We can utilize this as the base image:  https://store.docker.com/community/images/cromo/uncrustify/dockerfile

or

We build uncrustify into the unibeautify/uncrustify image

**Comment by Glavin001** [comment]
I am extremely disappointed someone would remove their Docker image from Docker Hub as they did. I think from here on, I prefer we copy as much of the original `Dockerfile` as possible, with the exception of Official Docker Images. I do not even have a copy of the `sonatest/docker-uncrustify` Dockerfile instructions... 👎

**Comment by stevenzeck** [comment]
https://bitbucket.org/sonatest-soft/docker-uncrustify/src/80ba5ca9b8d1f4682729035cb1f4dadcedc44815/Dockerfile?at=master&fileviewer=file-view-default

```
FROM alpine:latest
MAINTAINER Maxime Roussin-BÃ©langer "roussinm@sonatest.com"

ENV UNCRUSTIFY_VERSION 0.64

RUN apk upgrade --update

RUN apk add --no-cache make bash curl tar build-base cmake

RUN curl -fSL "https://github.com/uncrustify/uncrustify/archive/uncrustify-$UNCRUSTIFY_VERSION.tar.gz" -o uncrustify.tar.gz  \
	&& readonly NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || echo 1) \
	&& echo "Using upto $NPROC threads" \
	&& mkdir -p /usr/src/uncrustify \
	&& tar -xf uncrustify.tar.gz -C /usr/src/uncrustify --strip-components=1 \
	&& rm uncrustify.tar.gz* \
	&& dir="$(mktemp -d)" \
	&& cd "$dir" \
	&& cmake /usr/src/uncrustify \
	&& make -j$NPROC \
	&& make install \
	&& rm -rf "$dir" \
	&& rm -rf /usr/src/uncrustify
```

**Comment by stevenzeck** [comment]
> I think from here on, I prefer we copy as much of the original Dockerfile as possible, with the exception of Official Docker Images.

I concur.  Looks like php-cs-fixer, phpcs, and rscript are ones to keep an eye on.

Any objection to setting Travis to run these as a cron job once a month?

**Comment by Glavin001** [comment]
> https://bitbucket.org/sonatest-soft/docker-uncrustify/src/80ba5ca9b8d1f4682729035cb1f4dadcedc44815/Dockerfile?at=master&fileviewer=file-view-default

![image](https://user-images.githubusercontent.com/1885333/31313586-865c459e-abbd-11e7-88b5-938a643db86d.png)


> Any objection to setting Travis to run these as a cron job once a month?

Excellent idea. Setting up now.

**Comment by Glavin001** [comment]
Done.

![image](https://user-images.githubusercontent.com/1885333/31313599-d2be91da-abbd-11e7-873c-108379920e2c.png)

**Comment by stevenzeck** [comment]
I started it:  https://github.com/szeck87/docker-beautifiers/commit/5b51014fff5afa301e2784ff6f54c08e66d64b17

Basically the same thing as the original base image, but had to install python into alpine.
